name: main

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Define variables
        run: |
          echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install
        run: |
          npm install --no-package-lock
          npm install zx@${{ env.VERSION }}
      - name: Build
        run: npm run build
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USERNAME }}
          npm run build
          cd src
          npm version ${{ env.VERSION }}
          npx ci-publish
          git push --follow-tags origin HEAD:master
